-- ============================================================
-- GLOWCARE CRM — SQL MIGRATION
-- Eksekusi script ini di Supabase SQL Editor (https://supabase.com/dashboard)
-- ============================================================

-- 1. UPDATE TABEL users: Tambah kolom tier & points untuk CRM Loyalty
ALTER TABLE users 
  ADD COLUMN IF NOT EXISTS tier VARCHAR(50) DEFAULT 'Bronze',
  ADD COLUMN IF NOT EXISTS points INT DEFAULT 0;

-- 2. TABEL treatments (Katalog Menu Layanan Klinik)
CREATE TABLE IF NOT EXISTS treatments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    price NUMERIC NOT NULL,
    duration INT NOT NULL, -- Durasi dalam menit
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. TABEL bookings (Sistem Antrean & Log Transaksi)
CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    treatment_id BIGINT REFERENCES treatments(id) ON DELETE RESTRICT,
    booking_date TIMESTAMPTZ NOT NULL,
    status VARCHAR(50) DEFAULT 'Pending', -- 'Pending','Disetujui','Selesai','Batal'
    total_price NUMERIC NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. SEED DATA: Contoh treatment awal
INSERT INTO treatments (name, description, price, duration) VALUES
  ('Facial Deep Cleansing', 'Perawatan pembersihan wajah intensif untuk mengangkat komedo, minyak berlebih, dan sel kulit mati.', 150000, 45),
  ('Laser Brightening & Flek Therapy', 'Teknologi laser mutakhir untuk mencerahkan kulit, menyamarkan noda hitam dan bekas jerawat.', 500000, 60),
  ('Anti-Aging & Silk Peel Extraction', 'Perawatan pengencangan kulit dengan ekstraksi silk peel untuk mengurangi kerutan dan garis halus.', 750000, 90)
ON CONFLICT DO NOTHING;
